ccbc_library/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView

# Create a new class that redirects the user to the home page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self,request, user):
        return '/ccbclib/home/'

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'ccbclib.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ccbclib/',include('ccbclib.urls',namespace='ccbclib')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
)

ccbclib/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from ccbclib import views

urlpatterns = patterns('',
        #url(r'^$', views.index, name='index'),
        url(r'^about/$',views.about, name='about'),
        url(r'^home/$',views.home, name='home'),
        url(r'^borrow/$',views.bookborrow,name='borrow'),
        url(r'^return/$',views.bookreturn,name='return'),
        url(r'^renew/$',views.bookrenew,name='renew'),
        url(r'^success/$',views.success,name='success'),
        url(r'^infotable/(?P<dataToDisplay>\w+)/$',views.infotable,name='infotable'),
        #url(r'^book/add/$', views.BookCreate.as_view(),name='book_add'),
        #url(r'book/(?P<pk>[0-9]+)/$', views.BookUpdate.as_view(),name='book_update'),
        #url(r'book/(?P<pk>[0-9]+)/delete/$', views.BookDelete.as_view(),name='book_delete'),
        url(r'^borrower/$', views.BorrowerListView.as_view(),name='borrower_list'),
        url(r'^borrower/add/$', views.BorrowerCreate.as_view(),name='borrower_add'),
        url(r'^borrower/(?P<pk>[0-9]+)/$', views.BorrowerUpdate.as_view(),name='borrower_update'),
        )

urlpatterns += staticfiles_urlpatterns()

ccbclib/forms.py
from django import forms
from django.forms.extras.widgets import SelectDateWidget
from django.core.exceptions import ValidationError
from ccbclib.models import Book,Borrower,Transaction
import datetime
import autocomplete_light
from autocomplete_light.widgets import TextWidget

#import registration
#from django.contrib.auth.models import User

#Operations on Transaction model
class BorrowForm(forms.ModelForm):
    book = forms.ModelChoiceField(queryset=Book.objects.none())
    borrower = forms.ModelChoiceField(queryset=Borrower.objects.none())
    borrow_date = forms.DateField()
    #borrow_manager = forms.CharField(required=True,help_text="Manager's Initials")#change this to ChoiceField later
    
    def __init__(self,*args,**kwargs):
        super(BorrowForm,self).__init__(*args,**kwargs)
        #self.fields['book'] = forms.ModelChoiceField(queryset=Book.onshelf_books.all(),to_field_name="name",required=True,help_text='Book title')
        self.fields['borrower'] = forms.ModelChoiceField(queryset=Borrower.idle_borrowers.all(), to_field_name="name",required=True,help_text="Borrower's name")
        self.fields['borrow_date'] = forms.DateField(required=True,initial=datetime.date.today(),help_text='Borrow date',widget=SelectDateWidget())
        
    class Meta:
        model = Transaction
        fields = ('book','borrower','borrow_date')
        #exclude =('idtransaction','renew_date','renew_manager','return_date','return_manager',)

class BorrowFormAutoComplete(autocomplete_light.ModelForm):
    book = forms.ModelChoiceField(queryset=Book.objects.none())
    borrower = forms.ModelChoiceField(queryset=Borrower.objects.none())
    borrow_date = forms.DateField()
    
    def __init__(self,*args,**kwargs):
        super(BorrowFormAutoComplete,self).__init__(*args,**kwargs)
        self.fields['book'] = forms.ModelChoiceField(queryset=Book.objects.filter(quantity__gt=0),to_field_name="name",required=True,help_text='Book Title',widget=autocomplete_light.TextWidget('BookAutocomplete'))
        self.fields['borrower'] = forms.ModelChoiceField(queryset=Borrower.idle_borrowers.all(), to_field_name="name",required=True,help_text="Borrower's name")
        self.fields['borrow_date'] = forms.DateField(required=True,initial=datetime.date.today(),help_text='Borrow date',widget=SelectDateWidget())
        
    class Meta:
        model = Transaction
        fields = ('book','borrower','borrow_date')
        #autocomplete_names = {'book': 'BookAutocomplete'}
        autocomplete_fields = ('book',)

class BookDummyForm(autocomplete_light.ModelForm):
    #book = forms.ModelChoiceField(queryset=Book.objects.none())
    borrower = forms.ModelChoiceField(queryset=Borrower.objects.none())
    borrow_date = forms.DateField(required=True,initial=datetime.date.today(),help_text='Borrow date',widget=SelectDateWidget())
    
    def __init__(self,*args,**kwargs):
        super(BookDummyForm,self).__init__(*args,**kwargs)
        self.fields['book'] = forms.ModelChoiceField(queryset=Book.objects.filter(quantity__gt=0),to_field_name="name",required=True,help_text='Book title')
        self.fields['borrower'] = forms.ModelChoiceField(queryset=Borrower.idle_borrowers.all(), to_field_name="name",required=True,help_text="Borrower's name")
    #    self.fields['borrow_date'] = forms.DateField(required=True,initial=datetime.date.today(),help_text='Borrow date',widget=SelectDateWidget())
    
    class Meta:
        model = Transaction
        fields = ['book','borrower','borrow_date']

class RenewForm(forms.ModelForm):
    idtransaction = forms.ModelChoiceField(queryset=Transaction.objects.none())
    renew_date = forms.DateField()
    #renew_manager = forms.CharField(required=True,help_text="Manager's Initials")#change this to ChoiceField later
    
    def __init__(self,*args,**kwargs):
        super(RenewForm,self).__init__(*args,**kwargs)
        self.fields['idtransaction'] = forms.ModelChoiceField(queryset = Transaction.objects.filter(renew_date__isnull = True, return_date__isnull = True),help_text='Transaction')
        self.fields['renew_date'] = forms.DateField(required=True,initial=datetime.date.today(),widget=SelectDateWidget(),help_text='Renew Date')
        
    class Meta:
        model = Transaction
        fields = ('idtransaction','renew_date',)
        #exclude = ('book','borrower','borrow_date','borrow_manager','return_date','return_manager',)
        
class ReturnForm(forms.ModelForm):
    idtransaction = forms.ModelChoiceField(queryset = Transaction.objects.none())
    return_date = forms.DateField()
    #return_manager = forms.CharField(required=True,help_text="Manager's Initials")#change this to ChoiceField later
    
    def __init__(self,*args,**kwargs):
        super(ReturnForm,self).__init__(*args,**kwargs)
        self.fields['idtransaction'] = forms.ModelChoiceField(queryset = Transaction.objects.filter(return_date__isnull = True),help_text='Transaction')
        self.fields['return_date'] = forms.DateField(required=True,initial=datetime.date.today(),widget=SelectDateWidget(),help_text='Return Date')
        
    class Meta:
        model = Transaction
        fields = ('idtransaction','return_date',)
        #exclude = ('book','borrower','borrow_date','borrow_manager','renew_date','renew_manager',)

# Operations on Book model
"""
class BookForm(forms.Form):
    name = forms.CharField()
    code = forms.CharField()
"""
        

ccbclib/views.py
from django.shortcuts import render
from ccbclib.forms import BorrowForm, BorrowFormAutoComplete, ReturnForm, RenewForm, BookDummyForm
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse, reverse_lazy
from ccbclib.models import Book, Borrower, Transaction
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView
from django_tables2 import RequestConfig
from ccbclib.tables import BookTable, BorrowerTable, TransactionTable
#from statistics import mode
from django.contrib.auth.decorators import login_required
#from django.contrib.auth.models import User

def about(request):
    context_dict = {}
    return render(request, 'ccbclib/about.html', context_dict)

@login_required
def home(request):
    context_dict = {}
    return render(request, 'ccbclib/home.html', context_dict)

@login_required
def success(request):
    context_dict={}
    return render(request, 'ccbclib/operation_successful.html',context_dict)

@login_required
def bookborrow(request):
    staffname = get_staffname(request)
        
    # A HTTP POST?
    if request.method == 'POST':
        #form = BorrowForm(request.POST)
        #form = BorrowFormAutoComplete(request.POST)
        form = BookDummyForm(request.POST)
        # Have we been provided with a valid form?
        if form.is_valid():
            tmp_tran = form.save(commit=False)
            tmp_tran.borrow_manager = staffname
            
            #need to change the quantity of Book as well
            tmp_book = Book.objects.get(code_number=tmp_tran.book.code_number)
            tmp_book.quantity = tmp_tran.book.quantity-1
            tmp_book.save()
            
            tmp_tran.save()
            # Now call the index() view.
            # The user will be shown the homepage.
            return HttpResponseRedirect(reverse('ccbclib:success'))
        else:
            # The supplied form contained errors - just print them to the terminal.
            print(form.errors)
    else:
        # If the request was not a POST, display the form to enter details.
        #form = BorrowForm()
        #form = BorrowFormAutoComplete()
        form = BookDummyForm()
    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render(request, 'ccbclib/borrow.html', {'form': form,'staffname':staffname})

@login_required
def bookreturn(request):
    staffname = get_staffname(request)
        
    if request.method == 'POST':
        form = ReturnForm(request.POST)
        # Have we been provided with a valid form?
        if form.is_valid():
            transaction = Transaction.objects.get(pk=form.cleaned_data['idtransaction'].idtransaction)
            form = ReturnForm(request.POST, instance=transaction)
            tmp_tran = form.save(commit=False)
            tmp_tran.return_manager = staffname
            
            #need to change the quantity of Book as well
            tmp_book = Book.objects.get(code_number=tmp_tran.book.code_number)
            tmp_book.quantity = tmp_tran.book.quantity+1
            tmp_book.save()
            
            tmp_tran.save()
            # Now call the home() view.
            # The user will be shown the homepage.
            return HttpResponseRedirect(reverse('ccbclib:success'))
        else:
            print(form.errors)
    else:
        form = ReturnForm()

    return render(request, 'ccbclib/return.html', {'form': form,'staffname':staffname})

@login_required
def bookrenew(request):
    staffname = get_staffname(request)
        
    if request.method == 'POST':
        form = RenewForm(request.POST)
        # Have we been provided with a valid form?
        if form.is_valid():
            transaction = Transaction.objects.get(pk=form.cleaned_data['idtransaction'].idtransaction)
            form = RenewForm(request.POST, instance=transaction)
            tmp_tran = form.save(commit=False)
            tmp_tran.renew_manager = staffname
            tmp_tran.save()
            return HttpResponseRedirect(reverse('ccbclib:success'))
        else:
            print(form.errors)
    else:
        # If the request was not a POST, display the form to enter details.
        form = RenewForm()
        

    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render(request, 'ccbclib/renew.html', {'form': form,'staffname':staffname})

@login_required
def infotable(request,dataToDisplay):
    if dataToDisplay == 'transactions':
        table = TransactionTable(Transaction.objects.all())
        RequestConfig(request).configure(table)
        context_dict = {
                   "info_title" : "Transactions",
                   "table" : table
                   }
    elif dataToDisplay == 'books':
        table = BookTable(Book.objects.all())
        RequestConfig(request).configure(table)
        context_dict = {
                   "info_title": "Books",
                   "table" : table
                   }
    elif dataToDisplay == 'borrowers':
        table = BorrowerTable(Borrower.objects.all())
        RequestConfig(request).configure(table)
        context_dict = {
                   "info_title": "Borrowers",
                   "table" : table
                   }
    else:
        return HttpResponse("Cannot find resources specified.")
    
    return render(request,"ccbclib/info_table.html",context_dict)


##django's built-in generic view.
# CRUD for Book model
"""
# We may not want to add/modify/delete a book in normal applications - or set higher permission for this?

class BookCreate(CreateView):
    model = Book
    fields = ['name','code']
    success_url = reverse_lazy('ccbclib:success')

class BookUpdate(UpdateView):
    model = Book
    fields = ['name','code']

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('book-list')
"""
# CRUD for Borrower model

class BorrowerListView(ListView):
    model = Borrower


class BorrowerCreate(CreateView):
    model = Borrower
    fields = ['name','phone','email','cellgroup']
    success_url = reverse_lazy('ccbclib:success')


class BorrowerUpdate(UpdateView):
    model = Borrower
    fields = ['name','phone','email','cellgroup']
    success_url = reverse_lazy('ccbclib:success')

"""
class BorrowerDelete(DeleteView):
    model = Borrower
    fields = ['name','phone','email','cellgroup']
    success_url = reverse_lazy('ccbclib:success')
"""
# No easy generic edit views for Transaction model

#Some custom functions
def get_staffname(request):
    staffname = request.user.get_full_name()
    if staffname=="":
        staffname = request.user.get_username()
    return staffname

ccbc_library/templates/ccbclib/about.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}About{% endblock %}

{% block body_block %}
    <div class="page-header">
                <h1>About</h1>
            </div>
            <div>
            <p>This is the about page of <strong>CCBC Library</strong>!</p>
            </div>
{% endblock %}

ccbc_library/templates/ccbclib/book_form.html
{% extends 'base.html' %}

{% block title %}Add/Update a book{% endblock %}

{% block body_block %}
    <div class="page-header">
                <h1>Add/Update a book</h1><br />
                <h3>Please fill in the fields below:</h3>
    </div>
            <div>
			<form action="" method="post">{% csrf_token %}
    			{{ form.as_p }}
    			<input type="submit" value="Add/Update a book" />
			</form>
	</div>
{% endblock %}

ccbc_library/templates/ccbclib/borrow.html
{% extends 'base.html' %}

{% block title %}Borrow{% endblock %}

{% block body_block %}
    <div class="page-header">
                <h1>Borrow Form</h1><br />
                <h3>Please fill in the fields below:</h3>
    </div>
            <div>
            <form id="borrow_form" method="post" action="/ccbclib/borrow/">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}:
                {{ field }}
                <br />
                <br />
            {% endfor %}
            <p>Staff Name: {{ staffname }} </p>
            <input type="submit" name="submit" value="Borrow!" />
            </form>
            </div>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
    		{% include 'autocomplete_light/static.html' %}
{% endblock %}

ccbc_library/templates/ccbclib/borrower_form.html
{% extends 'base.html' %}

{% block title %}Add/Update a borrower{% endblock %}

{% block body_block %}
    <div class="page-header">
                <h1>Add/Update a borrower</h1><br />
                <h3>Please fill in the fields below:</h3>
    </div>
            <div>
			<form action="" method="post">{% csrf_token %}
    			{{ form.as_p }}
    			<input type="submit" value="Add/Update a borrower" />
			</form>
	</div>
{% endblock %}

ccbc_library/templates/ccbclib/borrower_list.html
{% extends 'base.html' %}

{% block title %}Borrowers{% endblock %}

{% block body_block %}
    <div class="page-header">
         <h1>List of borrowers</h1><br />
    </div>
    <div class="table-responsive">
		<table class="table table-striped" border="2" style="width:100%">
		<tr>
			<th>Name</th>
			<th>Phone</th>
			<th>Email</th>
			<th>Cellgroup</th>
		</tr>
		{% for borrower in object_list %}
		<tr>
    		<td><a href="{% url 'ccbclib:borrower_update' pk=borrower.idborrower%}">{{ borrower.name }}</a></td> 
            <td>{{ borrower.phone }}</td>
            <td>{{ borrower.email }}</td>
            <td>{{ borrower.cellgroup }}</td>
        </tr>
		{% empty %}
    		<tr>No borrower yet.</tr>
		{% endfor %}
		
		</table>		
	</div>
	<div>
		<br /><a href="{% url 'ccbclib:borrower_add'%}"> Add a new borrower</a>
	</div>
{% endblock %}

ccbc_library/templates/ccbclib/confirmation.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load render_table from django_tables2 %}

{% block title %} Confirmation {% endblock %}

{% block body_block %}
        <div class="confirmation-box">
        <p>{{ message }}</p>
        <div>
            <a href="{{ prev_link }}">Cancel</a>
            <form action="{{ action_link }}" method="post">
                <input type="hidden" name="next" value="{{ prev_link }}" />
                <input type="submit" value="Send" />
            </form>
        </div>
    </div>
{% endblock %}

ccbc_library/templates/ccbclib/email_duesoon.html
<!DOCTYPE html>

<html lang="en">
  <head>
  	<meta charset="utf-8">
  </head>
  
  <body>
  	<div>
  	<p>Dear {{ name }},</p>
  	<p>
  	  This is a notice to remind you that the book <b>"{{ title }}"</b> will be due on <b>{{ due_date }}</b>.<br />
  	  Please remember to return it to the CCBC Library before due date, or if applicable, renew it.<br />
  	  <br />If you have already returned this book, please disregard this message.
  	</p>
  	<p>
  	  Kind regards,<br />
  	  CCBC Library team
  	</p>
  	</div>
  </body>
 </html>

ccbc_library/templates/ccbclib/email_overdue.html
<!DOCTYPE html>

<html lang="en">
  <head>
  	<meta charset="utf-8">
  </head>
  
  <body>
  	<div>
  	<p>Dear {{ name }},</p>
  	<p>
  	  This is a notice to remind you that the book <b>"{{ title }}"</b> is now overdue.<br /><br />
  	  It was due on <b>{{ due_date }}</b>.<br /><br />
  	  Please return it to the CCBC Library as soon as possible.
  	  <br />If you have already returned this book, please disregard this message.
  	</p>
  	<p>
  	  Kind regards,<br />
  	  CCBC Library team
  	</p>
  	</div>
  </body>
 </html>

ccbc_library/templates/ccbclib/email_summary.html
<!DOCTYPE html>

<html lang="en">
  <head>
  	<meta charset="utf-8">
  </head>
  
  <body>
  	<div>
  	<p>
  	  Compiled on <b>{{ time }}</b>:<br />
  	  {{ item_notice }} items needed to be notify.<br />
  	  {{ email_sent }} emails were sent.<br />
  	  {{ sms_sent }} SMS were sent.<br />
  	</p>
  	</div>
  </body>
 </html>

ccbc_library/templates/ccbclib/home.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Home{% endblock %}

{% block body_block %}
    <div class="page-header">
                <div class="jumbotron">
                	<h2>Welcome to CCBC Library!</h2>
                </div>
                <h3>I want to ...</h3>
    </div>
            <div class="row text-center">
              <div class="col-md-4 text-center">
            	<a href="{% url 'ccbclib:borrow'%}" class="btn btn-success btn-lg"> 
            	Borrow a book </a>
              </div>
              <div class="col-md-4 text-center">
            	<a href="{% url 'ccbclib:renew'%}" class="btn btn-success btn-lg"> 
            	Renew a book </a>
              </div>
              <div class="col-md-4 text-center">
                <a href="{% url 'ccbclib:return'%}" class="btn btn-success btn-lg"> 
                Return a book </a>
              </div>
            </div>
            <br /><br /><br />
            <div class="row text-center">
            	<a href="{% url 'ccbclib:borrower_list'%}"class="btn btn-danger btn-lg"> 
            	Add/View/Edit borrowers </a>
            </div>
{% endblock %}

ccbc_library/templates/ccbclib/info_table.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load render_table from django_tables2 %}

{% block title %}{{ info_title }}{% endblock %}

{% block body_block %}
        {% render_table table %}
{% endblock %}

ccbc_library/templates/ccbclib/operation_successful.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Successful{% endblock %}

{% block body_block %}
    <div class="page-header">
                <h1>Operation successful!</h1><br />
                <h3>You can click the link below to go back to home page.</h3>
    </div>
            <div>
            <li><a href="{% url 'ccbclib:home'%}"> Back to Home </a></li><br />
            </div>
{% endblock %}

ccbc_library/templates/ccbclib/renew.html
{% extends 'base.html' %}

{% block title %}Renew{% endblock %}

{% block body_block %}
    <div class="page-header">
                <h1>Renew Form</h1><br />
                <h3>Please fill in the fields below:</h3>
    </div>
            <div>
            <form id="return_form" method="post" action="/ccbclib/renew/">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}:
                {{ field }}
                <br />
                <br />
            {% endfor %}
            <p>Staff Name: {{ staffname }} </p>
            <input type="submit" name="submit" value="Renew!" />
            </form>
            </div>
{% endblock %}

ccbc_library/templates/ccbclib/return.html
{% extends 'base.html' %}

{% block title %}Return{% endblock %}

{% block body_block %}
    <div class="page-header">
                <h1>Return Form</h1><br />
                <h3>Please fill in the fields below:</h3>
    </div>
            <div>
            <form id="return_form" method="post" action="/ccbclib/return/">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}:
                {{ field }}
                <br />
                <br />
            {% endfor %}
            <p>Staff Name: {{ staffname }} </p>
            <input type="submit" name="submit" value="Return!" />
            </form>
            </div>
{% endblock %}