ccbc_library/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView

# Create a new class that redirects the user to the home page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self,request, user):
        return '/ccbclib/home/'

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'ccbclib.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ccbclib/',include('ccbclib.urls',namespace='ccbclib')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
)

ccbclib/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from ccbclib import views

urlpatterns = patterns('',
        #url(r'^$', views.index, name='index'),
        url(r'^about/$',views.about, name='about'),
        url(r'^home/$',views.home, name='home'),
        url(r'^borrow/$',views.bookborrow,name='borrow'),
        url(r'^return/$',views.bookreturn,name='return'),
        url(r'^renew/$',views.bookrenew,name='renew'),
        url(r'^success/$',views.success,name='success'),
        url(r'^infotable/(?P<dataToDisplay>\w+)/$',views.infotable,name='infotable'),
        #url(r'^book/add/$', views.BookCreate.as_view(),name='book_add'),
        #url(r'book/(?P<pk>[0-9]+)/$', views.BookUpdate.as_view(),name='book_update'),
        #url(r'book/(?P<pk>[0-9]+)/delete/$', views.BookDelete.as_view(),name='book_delete'),
        url(r'^borrower/$', views.BorrowerListView.as_view(),name='borrower_list'),
        url(r'^borrower/add/$', views.BorrowerCreate.as_view(),name='borrower_add'),
        url(r'^borrower/(?P<pk>[0-9]+)/$', views.BorrowerUpdate.as_view(),name='borrower_update'),
        )

urlpatterns += staticfiles_urlpatterns()

ccbc_library/templates/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>CCBC library - {% block title %}CCBC library{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "css/dashboard.css" %}" />
    <link rel="stylesheet" href="{{ STATIC_URL }}django_tables2/themes/paleblue/css/screen.css" />

    {% comment %}
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
    {% endcomment %}
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'ccbclib:home' %}">CCBC Library</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'ccbclib:home' %}">Home</a></li>
                {% if user.is_authenticated %}
				<li><a href="{% url 'auth_logout' %}?next=/accounts/login/">Logout</a></li>
                {% else %}
                <li><a href="{% url 'auth_login' %}">Login</a></li>
                {% endif %}
                <li><a href="{% url 'registration_register' %}">Registrer</a></li>
                <li><a href="{% url 'ccbclib:about' %}">About</a></li>
                {% comment %}
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'restricted' %}">Restricted Page</a></li>
                        <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li><a href="{% url 'add_category' %}">Add a New Category</a></li>
                    {% else %}
                        <li><a href="{% url 'registration_register' %}">Register Here</a></li>
                        <li><a href="{% url 'auth_login' %}">Login</a></li>
                    {% endif %}
                                <li><a href="{% url 'about' %}">About</a></li>
                {% endcomment %}
              </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
                {% block side_block %}
                <ul class="nav nav-pills nav-stacked">
        			<li class="active"><a href=" {% url 'ccbclib:home' %} ">Home</a></li>
        			
        			<li class="dropdown">
          			<a class="dropdown-toggle" data-toggle="dropdown" href="#">Check Database<span class="caret"></span></a>
          				<ul class="dropdown-menu">
            				<li><a href=" {% url 'ccbclib:infotable' 'books'%} ">Books</a></li>
                			<li><a href=" {% url 'ccbclib:infotable' 'borrowers'%} ">Borrowers</a></li>
                			<li><a href=" {% url 'ccbclib:infotable' 'transactions'%} ">Transactions</a></li>
                		</ul>
                	</li>
                	<li class="dropdown">
      			  	<a class="dropdown-toggle" data-toggle="dropdown" href="#">Services<span class="caret"></span></a>
      			  	    <ul class="dropdown-menu">
      			    		<li><a href="{% url 'ccbclib:borrow'%}"> Borrow</a></li>
            				<li><a href="{% url 'ccbclib:renew'%}"> Renew</a></li>
            				<li><a href="{% url 'ccbclib:return'%}"> Return</a></li>
            		</li>
     			 
                {% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
           <div>
                {% block body_block %}{% endblock %}
                </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
    {% include 'autocomplete_light/static.html' %}
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

ccbc_library/templates/base_backup.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>CCBC library - {% block title %}CCBC library{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "css/dashboard.css" %}" />
    <link rel="stylesheet" href="{{ STATIC_URL }}django_tables2/themes/paleblue/css/screen.css" />

    {% comment %}
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
    {% endcomment %}
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'ccbclib:home' %}">CCBC Library</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'ccbclib:home' %}">Home</a></li>
                {% if user.is_authenticated %}
				<li><a href="{% url 'auth_logout' %}?next=/accounts/login/">Logout</a></li>
                {% else %}
                <li><a href="{% url 'auth_login' %}">Login</a></li>
                {% endif %}
                <li><a href="{% url 'registration_register' %}">Registrer</a></li>
                <li><a href="{% url 'ccbclib:about' %}">About</a></li>
                {% comment %}
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'restricted' %}">Restricted Page</a></li>
                        <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li><a href="{% url 'add_category' %}">Add a New Category</a></li>
                    {% else %}
                        <li><a href="{% url 'registration_register' %}">Register Here</a></li>
                        <li><a href="{% url 'auth_login' %}">Login</a></li>
                    {% endif %}
                                <li><a href="{% url 'about' %}">About</a></li>
                {% endcomment %}
              </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
                {% block side_block %}
                <ul class="nav nav-pills nav-stacked">
        			<li class="active"><a href=" {% url 'ccbclib:home' %} ">Home</a></li>
        			
        			<li class="dropdown">
          			<a class="dropdown-toggle" data-toggle="dropdown" href="#">Check Database<span class="caret"></span></a>
          				<ul class="dropdown-menu">
            				<li><a href=" {% url 'ccbclib:infotable' 'books'%} ">Books</a></li>
                			<li><a href=" {% url 'ccbclib:infotable' 'borrowers'%} ">Borrowers</a></li>
                			<li><a href=" {% url 'ccbclib:infotable' 'transactions'%} ">Transactions</a></li>
                		</ul>
                	</li>
                	<li class="dropdown">
      			  	<a class="dropdown-toggle" data-toggle="dropdown" href="#">Services<span class="caret"></span></a>
      			  	    <ul class="dropdown-menu">
      			    		<li><a href="{% url 'ccbclib:borrow'%}"> Borrow</a></li>
            				<li><a href="{% url 'ccbclib:renew'%}"> Renew</a></li>
            				<li><a href="{% url 'ccbclib:return'%}"> Return</a></li>
            		</li>
     			 
                {% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
           <div>
                {% block body_block %}{% endblock %}
                </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
    {% include 'autocomplete_light/static.html' %}
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>